---
title: "ESM 244 Lab Week 2"
author: "Grace Brofman"
date: "1/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# For PCA:
library(ggfortify)

# For ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures:
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp()

penguin_pca$rotation 

penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

# create a biplot of PCA

autoplot(penguin_pca,
         data = penguin_complete,
         colour = "species",
         loadings = TRUE,
         loadings.label = TRUE) +
  theme_minimal()
```

### Part 2: ggplot2 customization and reading in different file types

#### Read in an .xlsx file and do some wrangling

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>% 
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% 
  filter(confidentiality == "public")

```

Make a customized graph: 
```{r}
fish_plot <- ggplot(data = fish_noaa,
                    aes(x = year,
                        y = pounds)) +
  geom_line(aes(color = nmfs_name),
            show.legend = FALSE) +
  theme_minimal()

fish_plot

# make interactive plot with ggplotly
ggplotly(fish_plot)


```
### Use gghighlight to highlight certain series
```{r}
ggplot(data = fish_noaa,
                    aes(x = year,y = pounds, group = nmfs_name)) +
  geom_line() +
  theme_minimal() +
  gghighlight(nmfs_name == "tunas") # matching name



ggplot(data = fish_noaa,
                    aes(x = year,y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() +
  gghighlight(max(pounds) > 1e8) # matching value (highlights any value in the dataset where the maximum value for pounds for that series is greater than 1 x 10^8)
```

#### Read in data from a URL, use "lubridate()", "mutate()", make a graph with months in logical order

```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtpdailyelectricitybclear.csv") %>% 
  clean_names()

# create a graph that shows by month, how much total kwh this water treatment plant uses
# first, r needs to understand that the date column is a date

monroe_ts <- monroe_wt %>% 
  mutate(date = mdy(date)) %>% 
  mutate(record_month = month(date)) %>% 
  mutate(month_name = month.abb[record_month]) %>% 
  mutate(month_name = fct_reorder(month_name, record_month))


#> class(monroe_ts$month_name)
#[1] "character"
#> unique(monroe_ts$month_name)
# [1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

ggplot(data = monroe_ts, 
       aes(month_name, y = total_k_wh)) +
  geom_jitter()
# months show up alphabetically at first bc a default in ggplot for characters is to show things alphabetically
# need to convert month name to factor, then set the order of that factor to match the order of the months (see line above -fourth mutate line)



```














